<?php

namespace generadorBundle\Repository;

/**
 * EmrpresaFCTRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmrpresaFCTRepository extends \Doctrine\ORM\EntityRepository
{
}
